version: '3.9'

services:
  sample-api:
    image: sample-api:latest
    container_name: sample-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend

networks:
  backend:
    external: true
